"use client";
import { useState, useEffect } from "react";
import "./globals.css";
import Link from "next/link";

// export const metadata = {
//   title: "Web Tutorials",
//   description: "Generated by Jinga",
// };

const ulStyle = "flex font-semibold";
const liStyle = "mx-2";

export default function RootLayout({ children }) {
  // export default async function RootLayout({ children }) {
  // const res = await fetch("http://localhost:9999/topics");

  // const topics = await res.json();
  // console.log(topics);
  // 기본적으로 server component로 인식하기때문에 react처럼 이렇게 쓰면 에러가 뜸
  // 최상단에 "use client"; 넣으면 client component로 인식함
  const [res, setRes] = useState([]);
  useEffect(() => {
    fetch("http://localhost:9999/topics").then((result) => {
      // fetch URL 오타 수정
      setRes(result.json());
    });
  }, []);

  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>
        </h1>
        {/* <ol className={ulStyle}>{top}</ol> */}
        {children}
        <ul className={ulStyle}>
          <li className={liStyle}>
            <a href="/create">CREATE</a>
          </li>
          <li className={liStyle}>
            <a href="/update/1">UPDATE</a>
          </li>
          <li className={liStyle}>
            <input type="button" value="DELETE" />
          </li>
        </ul>
      </body>
    </html>
  );
}
